entities=JFS,BLACKROCK_WMC,BLACKROCK_AMC
pdf.date.format=EEE_dd-MMM-yyyy hh:mm a

exclude.hostname.start_with=DR

elastic.username=elastic
elastic.password=Clover@123
elastic.host=10.100.0.199
elastic.port=9200

email.from=jflalert.monitoring@cloverinfotech.com
email.recipients=tmail74580@gmail.com
#email.recipients=tmail7458@gmail.com,suraj.vikhe@cloverinfotech.com
email.host=email.cloverinfotech.com
email.username=jflalert.monitoring@cloverinfotech.com
email.password=Clover#2024

#---------------Dev-------------------------------------------

pdf.file.path.jfs=src\\main\\resources\\reports\\JFS.pdf
pdf.file.path.blackrock_wmc=src\\main\\resources\\reports\\BLACKROCK_WMC.pdf
pdf.file.path.blackrock_amc=src\\main\\resources\\reports\\BLACKROCK_AMC.pdf

json.template.file.path.interval=src\\main\\resources\\query_json\\interval.json
json.template.file.path.overall=src\\main\\resources\\query_json\\overall.json
json.template.file.path.cpu=src\\main\\resources\\query_json\\cpu.json
json.template.file.path.memory=src\\main\\resources\\query_json\\memory.json
json.template.file.path.hardware=src\\main\\resources\\query_json\\hardware.json

#-------------Prod--------------------------------

#pdf.file.path.jfs=/elkapp/app/uptimereports/reports_pdf/JFS.pdf
#pdf.file.path.blackrock_wmc=/elkapp/app/uptimereports/reports_pdf/BLACKROCK_WMC.pdf
#pdf.file.path.blackrock_amc=/elkapp/app/uptimereports/reports_pdf/BLACKROCK_AMC.pdf
#
#json.template.file.path.interval=/elkapp/app/uptimereports/query_json/interval.json
#json.template.file.path.overall=/elkapp/app/uptimereports/query_json/overall.json
#json.template.file.path.cpu=/elkapp/app/uptimereports/query_json/cpu.json
#json.template.file.path.memory=/elkapp/app/uptimereports/query_json/memory.json
#json.template.file.path.hardware=/elkapp/app/uptimereports/query_json/hardware.json



